# CMake generated Testfile for 
# Source directory: /ccs/home/hm0/Pkgs/openmm/platforms/reference/tests
# Build directory: /ccs/home/hm0/Pkgs/openmm/build_openmm/platforms/reference/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestReferenceAndersenThermostat "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceAndersenThermostat")
add_test(TestReferenceBrownianIntegrator "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceBrownianIntegrator")
add_test(TestReferenceCMAPTorsionForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCMAPTorsionForce")
add_test(TestReferenceCMMotionRemover "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCMMotionRemover")
add_test(TestReferenceCheckpoints "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCheckpoints")
add_test(TestReferenceCompoundIntegrator "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCompoundIntegrator")
add_test(TestReferenceCustomAngleForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCustomAngleForce")
add_test(TestReferenceCustomBondForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCustomBondForce")
add_test(TestReferenceCustomCVForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCustomCVForce")
add_test(TestReferenceCustomCentroidBondForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCustomCentroidBondForce")
add_test(TestReferenceCustomCompoundBondForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCustomCompoundBondForce")
add_test(TestReferenceCustomExternalForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCustomExternalForce")
add_test(TestReferenceCustomGBForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCustomGBForce")
add_test(TestReferenceCustomHbondForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCustomHbondForce")
add_test(TestReferenceCustomIntegrator "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCustomIntegrator")
add_test(TestReferenceCustomManyParticleForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCustomManyParticleForce")
add_test(TestReferenceCustomNonbondedForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCustomNonbondedForce")
add_test(TestReferenceCustomTorsionForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceCustomTorsionForce")
add_test(TestReferenceDispersionPME "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceDispersionPME")
add_test(TestReferenceEwald "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceEwald")
add_test(TestReferenceGBSAOBCForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceGBSAOBCForce")
add_test(TestReferenceGayBerneForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceGayBerneForce")
add_test(TestReferenceHarmonicAngleForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceHarmonicAngleForce")
add_test(TestReferenceHarmonicBondForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceHarmonicBondForce")
add_test(TestReferenceKineticEnergy "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceKineticEnergy")
add_test(TestReferenceLangevinIntegrator "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceLangevinIntegrator")
add_test(TestReferenceLocalEnergyMinimizer "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceLocalEnergyMinimizer")
add_test(TestReferenceMonteCarloAnisotropicBarostat "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceMonteCarloAnisotropicBarostat")
add_test(TestReferenceMonteCarloBarostat "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceMonteCarloBarostat")
add_test(TestReferenceMonteCarloMembraneBarostat "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceMonteCarloMembraneBarostat")
add_test(TestReferenceNeighborList "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceNeighborList")
add_test(TestReferenceNonbondedForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceNonbondedForce")
add_test(TestReferencePeriodicTorsionForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferencePeriodicTorsionForce")
add_test(TestReferenceRBTorsionForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceRBTorsionForce")
add_test(TestReferenceRMSDForce "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceRMSDForce")
add_test(TestReferenceRandom "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceRandom")
add_test(TestReferenceSettle "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceSettle")
add_test(TestReferenceVariableLangevinIntegrator "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceVariableLangevinIntegrator")
add_test(TestReferenceVariableVerletIntegrator "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceVariableVerletIntegrator")
add_test(TestReferenceVerletIntegrator "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceVerletIntegrator")
add_test(TestReferenceVirtualSites "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestReferenceVirtualSites")
