# CMake generated Testfile for 
# Source directory: /ccs/home/hm0/Pkgs/openmm/plugins/amoeba/platforms/cuda/tests
# Build directory: /ccs/home/hm0/Pkgs/openmm/build_openmm/plugins/amoeba/platforms/cuda/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestCudaAmoebaAngleForceSingle "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaAngleForce" "single")
add_test(TestCudaAmoebaAngleForceMixed "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaAngleForce" "mixed")
add_test(TestCudaAmoebaAngleForceDouble "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaAngleForce" "double")
add_test(TestCudaAmoebaBondForceSingle "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaBondForce" "single")
add_test(TestCudaAmoebaBondForceMixed "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaBondForce" "mixed")
add_test(TestCudaAmoebaBondForceDouble "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaBondForce" "double")
add_test(TestCudaAmoebaExtrapolatedPolarizationSingle "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaExtrapolatedPolarization" "single")
add_test(TestCudaAmoebaExtrapolatedPolarizationMixed "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaExtrapolatedPolarization" "mixed")
add_test(TestCudaAmoebaExtrapolatedPolarizationDouble "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaExtrapolatedPolarization" "double")
add_test(TestCudaAmoebaGeneralizedKirkwoodForceSingle "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaGeneralizedKirkwoodForce" "single")
add_test(TestCudaAmoebaGeneralizedKirkwoodForceMixed "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaGeneralizedKirkwoodForce" "mixed")
add_test(TestCudaAmoebaGeneralizedKirkwoodForceDouble "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaGeneralizedKirkwoodForce" "double")
add_test(TestCudaAmoebaInPlaneAngleForceSingle "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaInPlaneAngleForce" "single")
add_test(TestCudaAmoebaInPlaneAngleForceMixed "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaInPlaneAngleForce" "mixed")
add_test(TestCudaAmoebaInPlaneAngleForceDouble "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaInPlaneAngleForce" "double")
add_test(TestCudaAmoebaMultipoleForceSingle "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaMultipoleForce" "single")
add_test(TestCudaAmoebaMultipoleForceMixed "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaMultipoleForce" "mixed")
add_test(TestCudaAmoebaMultipoleForceDouble "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaMultipoleForce" "double")
add_test(TestCudaAmoebaOutOfPlaneBendForceSingle "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaOutOfPlaneBendForce" "single")
add_test(TestCudaAmoebaOutOfPlaneBendForceMixed "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaOutOfPlaneBendForce" "mixed")
add_test(TestCudaAmoebaOutOfPlaneBendForceDouble "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaOutOfPlaneBendForce" "double")
add_test(TestCudaAmoebaPiTorsionForceSingle "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaPiTorsionForce" "single")
add_test(TestCudaAmoebaPiTorsionForceMixed "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaPiTorsionForce" "mixed")
add_test(TestCudaAmoebaPiTorsionForceDouble "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaPiTorsionForce" "double")
add_test(TestCudaAmoebaStretchBendForceSingle "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaStretchBendForce" "single")
add_test(TestCudaAmoebaStretchBendForceMixed "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaStretchBendForce" "mixed")
add_test(TestCudaAmoebaStretchBendForceDouble "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaStretchBendForce" "double")
add_test(TestCudaAmoebaTorsionTorsionForceSingle "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaTorsionTorsionForce" "single")
add_test(TestCudaAmoebaTorsionTorsionForceMixed "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaTorsionTorsionForce" "mixed")
add_test(TestCudaAmoebaTorsionTorsionForceDouble "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaTorsionTorsionForce" "double")
add_test(TestCudaAmoebaVdwForceSingle "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaVdwForce" "single")
add_test(TestCudaAmoebaVdwForceMixed "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaVdwForce" "mixed")
add_test(TestCudaAmoebaVdwForceDouble "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaAmoebaVdwForce" "double")
add_test(TestCudaWcaDispersionForceSingle "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaWcaDispersionForce" "single")
add_test(TestCudaWcaDispersionForceMixed "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaWcaDispersionForce" "mixed")
add_test(TestCudaWcaDispersionForceDouble "/ccs/home/hm0/Pkgs/openmm/build_openmm/TestCudaWcaDispersionForce" "double")
